name: WeasyPrint
description: Converts HTML + CSS to PDF
license: BSD
public: true
url: http://www.weasyprint.org/
pystil: https://kozea.pystil.org/pystil.js

menu:
  - Overview:
      link: /
  - News:
      link: /news/
  - Documentation:
      link: /docs/
  - Install:
      link: /docs/install/
  - Community:
      link: /community/

footer:
  - A Kozea Project:
      link: http://community.kozea.fr/
  - Optimized for Standards:
      link: http://validator.w3.org/check?uri=referer

redirects:
    /install/: /docs/install/
    /using/: /docs/tutorial/
    /hacking/: /docs/hacking/
    /features/: /docs/features/

project (git):
  url: git://github.com/Kozea/WeasyPrint.git
  path: weasyprint

sphinx (git):
  url: git://github.com/Kozea/WeasyPrint.git
  path: weasyprint

vcs (git):
  url: git://github.com/Kozea/WeasyPrint.git
  path: /var/db/git/weasyprint.git

code browser (github):
  project name: Kozea/WeasyPrint
  ribbon: Fork me on GitHub

bug tracker (github):
  project name: Kozea/WeasyPrint

continuous integration (jenkins):
  base url: http://jenkins.kozea.org/
  project name: WeasyPrint
